CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(25)                             NOT NULL,
    surname   VARCHAR(25)                             NOT NULL,
    birthdate date                                    NOT NULL,
    username  VARCHAR(50)                             NOT NULL,
    email     VARCHAR(50)                             NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);