CREATE TABLE choices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        VARCHAR(2000)                           NOT NULL,
    question_id BIGINT                                  NOT NULL,
    correct     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_choices PRIMARY KEY (id)
);

ALTER TABLE choices
    ADD CONSTRAINT FK_CHOICES_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);